version: '2.0'


services:
  app2: 
    container_name: app2
    image: pppatil/gbcnodejsdocker
    ports:
     - 8000:80
    volumes:
     - ./shared:/usr/src/shared/
    networks:
     - gbc-network


networks:
  gbc-network:
    external: true
  


